### ISSUE TITLE
Should follow the original directives order

### ISSUE THREAD

**Issue by huozhi** [huozhi/rollup-plugin-swc-preserve-directives#6]
if you have two directives

```js
"use strict"

"use client"
```

### Expected

should output as 

```js
"use strict"
"use client"
```

### Observed

```js
"use client"
"use strict"
```

**Comment by SukkaW** [comment]
@huozhi What happens with this?

```tsx
// client/foo.tsx
'use client';
'use strict';

// client/bar.tsx
'use strict';
'use client';

// client/index.tsx
export * from './foo';
export * from './bar';
```

**Comment by huozhi** [comment]
Good example, it’s not doable after multi files bundling. Found it in one file bundling thought could be the snapshot consistent.

But if you’re using bundle everything strategy now usually you only put one directive at entry file cause there’s no code splitting.
